# Copyright (C) 2023 Aaron Yeoh Cruz <zeyonaut@gmail.com>
# SPDX-License-Identifier: CC0-1.0

group_imports = "StdExternalCrate"
hard_tabs = true
imports_granularity = "Crate"
match_block_trailing_comma = true
newline_style = "Unix"
max_width = 256